<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Mani" failures="0" tests="3" name="com.DataDriven.testCases.AddCustomerTest" time="10.992" errors="0" timestamp="2024-10-10T23:51:30 IST" skipped="1">
  <testcase classname="com.DataDriven.testCases.AddCustomerTest" name="addCustomerTest" time="0.000">
    <skipped/>
  </testcase> <!-- addCustomerTest -->
  <testcase classname="com.DataDriven.testCases.AddCustomerTest" name="addCustomerTest" time="5.639"/>
  <testcase classname="com.DataDriven.testCases.AddCustomerTest" name="addCustomerTest" time="5.353"/>
  <system-out>
    <![CDATA[<br>Verification failure : expected [abc] but found [xyz]<br>
<a target="_blank" href=Thu_Oct_10_23_51_08_IST_2024.jpg>Screenshot</a>
<br>
login successfully executed]]>
  </system-out>
</testsuite> <!-- com.DataDriven.testCases.AddCustomerTest -->
